name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build
        env:
          VITE_SUPABASE_URL: https://qllcfaignfyecakqzugu.supabase.co
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsbGNmYWlnbmZ5ZWNha3F6dWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzMDM3ODYsImV4cCI6MjA5Njg3OTc4Nn0.bWiu3V51LNeECMpZaFPNs60zCcZA6U4CwHyjCrORNJ0

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
